source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/keybindings.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/colors/gruvbox-dark.vim
source $HOME/.config/nvim/plug-config/completion.vim
source $HOME/.config/nvim/plug-config/nerdtree.vim
source $HOME/.config/nvim/plug-config/telescope.vim
source $HOME/.config/nvim/plug-config/nerdcommenter.vim
source $HOME/.config/nvim/plug-config/airline.vim
source $HOME/.config/nvim/plug-config/indentline.vim
source $HOME/.config/nvim/plug-config/cpp-enhanced-highlight.vim
source $HOME/.config/nvim/plug-config/auto-pairs.vim
source $HOME/.config/nvim/plug-config/vim-highlightedyank.vim
